src/MAM/RHBundle/Entity/CV.php
<?php

namespace MAM\RHBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * CV
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="MAM\RHBundle\Entity\CVRepository")
 * @ORM\HasLifecycleCallbacks
 */
class CV
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255,nullable=true)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255,nullable=true)
     */
    private $alt;

    private $file;

    private $tempFilename;


    public function setFile(UploadedFile $file)
    {
        $this->file = $file;
        if (null !== $this->url) {
            $this->tempFilename = $this->url;
            $this->url = null;
            $this->alt = null;
        }
    }
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null === $this->file) {
            return;
        }
        $this->url = $this->file->guessExtension();
        $this->alt = $this->file->getClientOriginalName();
    }
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->file) {
            return;
        }
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }
        $this->file->move($this->getUploadRootDir(), $this->id.'.'.$this->url);
    }
    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if (file_exists($this->tempFilename)) {
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        return 'uploads/cv';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }

    public function getFile()
    {
        return $this->file;
    }
}

src/MAM/RHBundle/Controller/RHController.php
<?php

namespace MAM\RHBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Security\Core\SecurityContext;

use MAM\UserBundle\Entity\User;

use FOS\UserBundle\Mailer\TwigSwiftMailer;

use MAM\RHBundle\Entity\ResponsableRH;
use MAM\RHBundle\Entity\Employenormal;
use MAM\RHBundle\Entity\Attestation;
use MAM\RHBundle\Entity\Employe;
use MAM\RHBundle\Entity\ChefDepartement;
use MAM\RHBundle\Entity\Departement;

use MAM\RHBundle\Entity\Offre;
use MAM\RHBundle\Entity\Stagiaire;

use MAM\RHBundle\Form\EmployeType;
use MAM\RHBundle\Form\OffreType;
use MAM\RHBundle\Form\StagiaireType;


class RHController extends Controller
{
    public function AcceuilAction()
    {
        $id = $this->getUser()->getEmploye()->getId();

        $em = $this->getDoctrine()->getManager();

        $demandenonv = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandenonV($this->getUser());

        $demandev = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandeV($this->getUser());

        if ($this->get('security.context')->isGranted('ROLE_EMP')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojet($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_PROJET')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetchef($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_DEP')){
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetdep($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_RH')){
            $nbrprojet[0][1] = 0;
        }

        $nbrstagiaire = $em->getRepository('MAMRHBundle:Stagiaire')
            ->getnbrprojet($this->getUser());

        return $this->render('MAMRHBundle:RH:Acceuil.html.twig',array(
            'demandenonv'=>$demandenonv[0][1],
            'demandev'=>$demandev[0][1],
            'nbrprojet'=>$nbrprojet[0][1],
            'nbrstagiaire'=>$nbrstagiaire[0][1],'id' => $id));
    }
    public function ajoutemployeAction()
    {
        $employe = new Employenormal();
        $form = $this->createForm(new EmployeType(),$employe);
        $request = $this->get('request');

        $em = $this->getDoctrine()->getManager();

        $demandenonv = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandenonV($this->getUser());

        $demandev = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandeV($this->getUser());

        if ($this->get('security.context')->isGranted('ROLE_EMP')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojet($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_PROJET')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetchef($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_DEP')){
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetdep($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_RH')){
            $nbrprojet[0][1] = 0;
        }

        $nbrstagiaire = $em->getRepository('MAMRHBundle:Stagiaire')
            ->getnbrprojet($this->getUser());

        if ($request->getMethod() == 'POST') {
            $form->submit($request);
            if ($form->isValid()) {
                $tokenGenerator = $this->container->get('fos_user.util.token_generator');
                $userManager = $this->container->get('fos_user.user_manager');
                $user = $userManager->createUser();

                $dep = $this->getDoctrine()
                    ->getManager()
                    ->getRepository('MAMRHBundle:Departement')
                    ->find($employe->getDepartement()->getId());
                //if($dep instanceof Departement) var_dump($dep);

                $dep->addEmploye($employe);
                $user->setRoles(array('ROLE_EMP'));
                $employe->setMatricule(substr($tokenGenerator->generateToken(), 0, 6));
                $employe->setDateEmbauche(new \Datetime());
                $employe->setBye(false);
                $user->setEmail($employe->getEmail());
                $user->setUsername($employe->getEmail());
                $passhelp=substr($tokenGenerator->generateToken(), 0, 10);
                $user->setPlainPassword($passhelp);
                $user->setEnabled(true);
                $user->setEmploye($employe);
                $employe->setUser($user);
                //var_dump($employe);

                $em->persist($employe);
                $em->persist($user);


                if($this->confirmation($user,$passhelp)) $em->flush();
                else throw new AccessDeniedHttpException('Email non envoyer');


                $this->get('session')->getFlashBag()->add('info', 'Employé bien ajouté');
                //var_dump($user);

                return $this->redirect($this->generateUrl('mamrh_ajoutemploye'));
            }
        }
        $id = $this->getUser()->getEmploye()->getId();
        return $this->render('MAMRHBundle:RH:AjoutEmploye.html.twig',array('form' => $form->createView(),
            'demandenonv'=>$demandenonv[0][1],
            'demandev'=>$demandev[0][1],
            'nbrprojet'=>$nbrprojet[0][1],
            'nbrstagiaire'=>$nbrstagiaire[0][1],'id'=>$id));
    }

    public function ajoutoffreAction()
    {
        $id = $this->getUser()->getEmploye()->getId();
        $offre = new Offre();
        $form = $this->createForm(new OffreType(), $offre);
        $request = $this->get('request');


        $em = $this->getDoctrine()->getManager();

        $demandenonv = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandenonV($this->getUser());

        $demandev = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandeV($this->getUser());

        if ($this->get('security.context')->isGranted('ROLE_EMP')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojet($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_PROJET')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetchef($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_DEP')){
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetdep($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_RH')){
            $nbrprojet[0][1] = 0;
        }

        $nbrstagiaire = $em->getRepository('MAMRHBundle:Stagiaire')
            ->getnbrprojet($this->getUser());

        if ($request->getMethod() == 'POST') {
            $form->submit($request);
            if ($form->isValid()) {

                $rh = $em->getRepository('MAMRHBundle:ResponsableRH')->find($this->getUser());
                //var_dump($rh);
                $offre->setResponsableRH($rh);

                $em->persist($offre);
                $em->flush();
                $this->get('session')->getFlashBag()->add('info', 'Offre bien ajouté');


                return $this->redirect($this->generateUrl('mamrh_Listoffre'));
            }
        }
        return $this->render('MAMRHBundle:RH:AjoutOffre.html.twig',array('form' => $form->createView(),
            'demandenonv'=>$demandenonv[0][1],
            'demandev'=>$demandev[0][1],
            'nbrprojet'=>$nbrprojet[0][1],
            'nbrstagiaire'=>$nbrstagiaire[0][1],'id'=>$id));
    }
    public function getemployenormalAction()
    {
        $em = $this->getDoctrine()->getManager();
        $entities=$this->getDoctrine()
                ->getManager()
                ->getRepository('MAMRHBundle:Employe')
                ->getemployenormal();
        $i = 0;
        //var_dump($entities);
        $e = array();
        foreach($entities as $en){
            //$query = "SELECT dtype FROM employe WHERE id=".$e->getId();
            //$dtype[$i] = $em->getConnection()->exec($query);

            $connection = $em->getConnection();
            $statement = $connection->prepare("SELECT dtype FROM employe WHERE id = :id");
            $statement->bindValue('id', $en->getId());
            $statement->execute();
            $dtype[$i] = $statement->fetchAll();

            //array_push($e,$dtype[$i],$en);

            $i++;
        }
        //var_dump($e);
        //var_dump($dtype[0][0]['dtype']);

        $id = $this->getUser()->getEmploye()->getId();

        $demandenonv = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandenonV($this->getUser());

        $demandev = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandeV($this->getUser());

        if ($this->get('security.context')->isGranted('ROLE_EMP')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojet($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_PROJET')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetchef($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_DEP')){
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetdep($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_RH')){
            $nbrprojet[0][1] = 0;
        }
        $nbrstagiaire = $em->getRepository('MAMRHBundle:Stagiaire')

src/MAM/RHBundle/Resources/views/RH/Acceuil.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Tableau de Bord{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}

{% block corps %}

<div class="col-lg-8">

<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-clock-o fa-fw"></i> Responsive Timeline
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <ul class="timeline">
            <li>
                <div class="timeline-badge"><i class="fa fa-check"></i>
                </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="timeline-title">Lorem ipsum dolor</h4>
                        <p><small class="text-muted"><i class="fa fa-clock-o"></i> 11 hours ago via Twitter</small>
                        </p>
                    </div>
                    <div class="timeline-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero laboriosam dolor perspiciatis omnis exercitationem. Beatae, officia pariatur? Est cum veniam excepturi. Maiores praesentium, porro voluptas suscipit facere rem dicta, debitis.</p>
                    </div>
                </div>
            </li>
            <li class="timeline-inverted">
                <div class="timeline-badge warning"><i class="fa fa-credit-card"></i>
                </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="timeline-title">Lorem ipsum dolor</h4>
                    </div>
                    <div class="timeline-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem quibusdam, tenetur commodi provident cumque magni voluptatem libero, quis rerum. Fugiat esse debitis optio, tempore. Animi officiis alias, officia repellendus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium maiores odit qui est tempora eos, nostrum provident explicabo dignissimos debitis vel! Adipisci eius voluptates, ad aut recusandae minus eaque facere.</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="timeline-badge danger"><i class="fa fa-bomb"></i>
                </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="timeline-title">Lorem ipsum dolor</h4>
                    </div>
                    <div class="timeline-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus numquam facilis enim eaque, tenetur nam id qui vel velit similique nihil iure molestias aliquam, voluptatem totam quaerat, magni commodi quisquam.</p>
                    </div>
                </div>
            </li>
            <li class="timeline-inverted">
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="timeline-title">Lorem ipsum dolor</h4>
                    </div>
                    <div class="timeline-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates est quaerat asperiores sapiente, eligendi, nihil. Itaque quos, alias sapiente rerum quas odit! Aperiam officiis quidem delectus libero, omnis ut debitis!</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="timeline-badge info"><i class="fa fa-save"></i>
                </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="timeline-title">Lorem ipsum dolor</h4>
                    </div>
                    <div class="timeline-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis minus modi quam ipsum alias at est molestiae excepturi delectus nesciunt, quibusdam debitis amet, beatae consequuntur impedit nulla qui! Laborum, atque.</p>
                        <hr>
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-gear"></i>  <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Action</a>
                                </li>
                                <li><a href="#">Another action</a>
                                </li>
                                <li><a href="#">Something else here</a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="timeline-title">Lorem ipsum dolor</h4>
                    </div>
                    <div class="timeline-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi fuga odio quibusdam. Iure expedita, incidunt unde quis nam! Quod, quisquam. Officia quam qui adipisci quas consequuntur nostrum sequi. Consequuntur, commodi.</p>
                    </div>
                </div>
            </li>
            <li class="timeline-inverted">
                <div class="timeline-badge success"><i class="fa fa-graduation-cap"></i>
                </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="timeline-title">Lorem ipsum dolor</h4>
                    </div>
                    <div class="timeline-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt obcaecati, quaerat tempore officia voluptas debitis consectetur culpa amet, accusamus dolorum fugiat, animi dicta aperiam, enim incidunt quisquam maxime neque eaque.</p>
                    </div>
                </div>
            </li>
        </ul>
</div>
</div>

</div>
{% endblock %}

src/MAM/RHBundle/Resources/views/RH/AjoutOffre.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Ajouter une Offre{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}

{% block corps %}
    <div class="col-lg-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <i class="fa fa-edit"></i>
                &nbsp;Formulaire d'ajout d'un offre
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-8">
                        <div >
                            <form method="post" {{ form_enctype(form) }}>
                                {{ form_errors(form) }}
                                <div class="form-group">
                                    <label>{{ form_label(form.typeoffre, "Le type de L'offre") }}</label>
                                    <div class="form-control">
                                        {{ form_widget(form.typeoffre) }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>{{ form_label(form.libelle, "Libellé de l'offre ") }}</label>
                                    <div class="form-control">
                                        {{ form_widget(form.libelle) }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>{{ form_label(form.descriptif, "Description ") }}</label>

                                        {{ form_widget(form.descriptif) }}

                                </div>
                                <button type="submit" class="btn btn-outline btn-primary">Envoyer</button>
                                {{ form_rest(form) }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/MAM/RHBundle/Resources/views/RH/ArchiveEmp.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Archive des employés{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}

{% block corps %}
<div class="col-lg-12">
    <div class="panel panel-primary">
       <div class="panel-heading">
           <i class="fa fa-th-list"></i>
           Tableau d'historique
       </div>
       <div class="panel-body">
           <div class="dataTable_wrapper">
               <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                     <thead>
                      <tr>
                          <th>Matricule</th>
                          <th>Nom</th>
                          <th>Prénom</th>
                          <th>Fonction</th>
                          <th>Département</th>
                          <th>Résponsabilité</th>
                      </tr>
                     </thead>
                   {% set i = 0 %}

                     <tbody>
                     {% for employe in entities %}
                       <tr class="odd gradeX">
                           <td>{{ employe.Matricule }}</td>
                           <td>{{ employe.Nom }}</td>
                           <td>{{ employe.Prenom }}</td>
                           <td>{{ employe.Fonction }}</td>
                           <td>{{ employe.departement.Libelle }}</td>

                           {% if(dtype[i][0]['dtype'] == 'Employenormal') %}
                               <td>Employe</td>
                           {% else %}
                               <td>{{ dtype[i][0]['dtype'] }}</td>
                           {% endif %}

                       </tr>
                         {% set i = i+1 %}

                     {% endfor %}
                     </tbody>

               </table>
           </div>
       </div>
    </div>
</div>
{% endblock %}
{% block panel %}
{% endblock %}

src/MAM/RHBundle/Resources/views/RH/Candidat.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Suivis{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}


{% block corps %}
    {{ entities.CIN }}
    {{ entities.Nom }}
    {{ entities.Prenom }}
    {{ entities.Email }}
    {{ entities.Specialite }}
    {{ entities.Diplome }}
    {{ entities.Tel }}
    {{ asset(entities.cv.webPath) }}
    {% block panel %}
    {% endblock  %}
{% endblock %}

src/MAM/RHBundle/Resources/views/RH/affichestagiaire.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Liste des stagiaires{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}

{% block corps %}
<div class="col-lg-12">
    <div class="panel panel-primary">
       <div class="panel-heading">
           <i class="fa fa-list-alt"></i>
           Tableau des stagiaires
       </div>
       <div class="panel-body">
           <div class="dataTable_wrapper">
               <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Adresse</th>
                        <th>Téléphone</th>
                        <th>Sujet</th>
                        <th>Date début</th>
                        <th>Date fin</th>
                        <th>CV</th>
                        <th>Opérations</th>
                    </tr>
                    </thead>
                    {% for stagiaire in entities %}
                    <tbody>
                    <tr class="odd gradeX">
                        <td>{{ stagiaire.Nom }}</td>
                        <td>{{ stagiaire.Prenom }}</td>
                        <td>{{ stagiaire.Adresse }}</td>
                        <td>{{ stagiaire.Tel }}</td>
                        <td>{{ stagiaire.sujet }}</td>
                        <td>{{ stagiaire.datedeb|date('d/m/Y') }}</td>
                        <td>{{ stagiaire.datefin|date('d/m/Y') }}</td>
                        <td align="center"><a href="{{ asset(stagiaire.cv.webPath) }}"><i class="fa fa-download"></i></a></td>
                        <td align="center">
                            <a href="{{ path('mamrh_editstagiaire', {'id' : stagiaire.id}) }}">
                                <i class="fa fa-edit"></i>
                            </a>  &nbsp;&nbsp;
                        </td>

                    </tr>
                    </tbody>
                    {% endfor %}
               </table>
           </div>
       </div>
    </div>
    </div>
    {% block panel %}
    {% endblock  %}
{% endblock %}

src/MAM/RHBundle/Resources/views/RH/archivestagiaire.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Liste des stagiaires{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}

{% block corps %}
<div class="col-lg-12">
    <div class="panel panel-primary">
       <div class="panel-heading">
           <i class="fa fa-list-alt"></i>
           Tableau des stagiaires
       </div>
       <div class="panel-body">
           <div class="dataTable_wrapper">
               <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Adresse</th>
                        <th>Téléphone</th>
                        <th>Sujet</th>
                        <th>Date début</th>
                        <th>Date fin</th>
                        <th>CV</th>
                    </tr>
                    </thead>
                    {% for stagiaire in entities %}
                    <tbody>
                    <tr class="odd gradeX">
                        <td>{{ stagiaire.Nom }}</td>
                        <td>{{ stagiaire.Prenom }}</td>
                        <td>{{ stagiaire.Adresse }}</td>
                        <td>{{ stagiaire.Tel }}</td>
                        <td>{{ stagiaire.sujet }}</td>
                        <td>{{ stagiaire.datedeb|date('d/m/Y') }}</td>
                        <td>{{ stagiaire.datefin|date('d/m/Y') }}</td>
                        <td align="center"><a href="{{ asset(stagiaire.cv.webPath) }}"><i class="fa fa-download"></i></a></td>


                    </tr>
                    </tbody>
                    {% endfor %}
               </table>
           </div>
       </div>
    </div>
    </div>
    {% block panel %}
    {% endblock  %}
{% endblock %}